// src/utils/evaluator.ts
// Evaluator for AST generated by parser.ts.
// Provides evaluateExpression(string) that parses and evaluates the expression.

import { ASTNode, NumberNode, BinaryNode, parseExpression } from './parser';

/**
 * Recursively evaluates an AST node and returns its numeric value.
 * Throws an Error with a descriptive message for runtime errors (e.g., division by zero).
 */
export function evaluateAST(node: ASTNode): number {
  switch (node.type) {
    case 'Number':
      return node.value;
    case 'BinaryExpression': {
      const left = evaluateAST(node.left);
      const right = evaluateAST(node.right);
      switch (node.operator) {
        case '+':
          return left + right;
        case '-':
          return left - right;
        case '*':
          return left * right;
        case '/':
          if (right === 0) {
            throw new Error('Division by zero');
          }
          return left / right;
        default:
          // Should never happen due to type constraints
          const _exhaustiveCheck: never = node.operator;
          return _exhaustiveCheck;
      }
    }
    default:
      const _exhaustiveCheck: never = node as never;
      return _exhaustiveCheck;
  }
}

/**
 * Parses and evaluates an arithmetic expression string.
 * Returns the numeric result.
 * Throws SyntaxError for parsing errors or Error for runtime evaluation errors.
 */
export function evaluateExpression(expr: string): number {
  const ast = parseExpression(expr);
  return evaluateAST(ast);
}
